spring:
  application:
    name: mq-exercise

  kafka:
    bootstrap-servers:
      - 106.75.14.33:9093
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: test
